sudo: required
dist: xenial
language: python
cache: pip
python:
- '2.7'
- '3.4'
- '3.5'
- '3.5-dev'
- '3.6'
- '3.6-dev'
- '3.7'
- '3.7-dev'
- '3.8-dev'
- 'nightly'
- 'pypy'
- 'pypy3'
matrix:
  fast_finish: true
  allow_failures:
  - python: 3.5-dev
  - python: 3.6-dev
  - python: 3.7-dev
  - python: 3.8-dev
  - python: nightly
  - python: pypy
  - python: pypy3
addons:
  apt:
    packages:
    - texlive-base
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-publishers
    - texlive-latex-extra
install:
- pip install -r requirements.txt
script:
- python setup.py test
notifications:
  email:
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: sadok
  password:
    secure: "WNSG3LM7hAxRvAdXnF6WaNjL80Bka78gdHB+tPXAmSmu0bFMHBRZwoQqF6SWpFkh3gil+ROl80bU7r1Yy8s32Z7kTBtQl9HPHwax65TEvixhTs6IgsjM22xPYYhxwowH7oteUKnApR14bW3VLtfWtEWrKR/XK+FqclT/vB0C8X1YP+iTFsQ8qjdybzBwvwXR8MeMqdoTyfp4Gr1D2cvOjQQMiOnjbZ5+MXsJN2QykDN94quuUKkWQamLukKFAK76+z1QRhp852YCTaw2gkhZfmyecADpr4QZrrj4U15LvAmTrjp1KL9bJwnS57UUIT0JQic4DeO4oo3FO2fxB1F3iHR3O7Xo6jYFxN8ZrXLrY/V0r72rFXXpe+eJBXnDOf0ERwUgI3NGs8wII9WGG0VI26Tau1zUj+pzF/6aFh01sJo088hC+JhhDPLN01LKnXlL23uDEBk6+dES3A88eTd0z+o6GrrrHVt5HtBkHIxNUNufzitW4zzLLaXdCw5CabqZXx4MrZumLzcSYjdd2bHphJvoXUC2a4AKYMQMToRohOEx8iLnRuAQZ5b/yuUMy89Ri2bNfiDQHxEdyZy36G9TRFg9DO0wJkm2TmJ8EUAoBZ89ugAA0xOG4ZljdaEGzrkeirS1aXLZy/8T2A0jNBD+CClUqbJ5ZNIeSf3HDKqdNLg="
  on:
    tags: true
    python: 3.6
